### ISSUE TITLE
Scheduling Issue for Week 2

### ISSUE THREAD

**Issue by kingcons** [kingcons/study-group#3]
Dear Doges,

It's been brought to my attention that our beloved @bigjust wouldn't be able to make this Wednesday's session. I was wondering what thoughts y'all have about doing another night. I lean Monday or Tuesday but Thursday might also be possible. What say ye @Christophin and @mlsimpson?

:heart:s and λs,
KingCons

**Comment by Christophin** [comment]
Prefer Thursday, can do Tuesday. Can't do today, prepping for an interview tomorrow.

**Comment by Christophin** [comment]
Also what is that, love and lambda's??

**Comment by kingcons** [comment]
Hell yeah, love and lambdas. And I talked to Matt and he can do Thursday. Just waiting for final confirmation from @bigjust.

**Comment by kingcons** [comment]
Alright, I've got confirmation. Meeting will be at 6pm Thursday, August the 2nd this week. <3
